blank_issues_enabled: true
contact_links:
  - name: "❔ Start a Discussion"
    about: Ask a general question or start a discussion
    url: https://github.com/django-files/web-extension/discussions

  - name: "💬 Join Discord"
    about: Chat with us about anything
    url: https://discord.gg/wXy6m2X8wY

  - name: "🌐 Django Files Website"
  - about: View the Django Files website
  - url: https://django-files.github.io/
